// react-ui-test/src/App.tsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'
// import { IconMaster } from '../../src/react'
import { IconMaster } from '../../dist/react'

function App () {
  const [count, setCount] = useState(0)

  return (
    <div className='App'>
      <IconMaster
        style={{ width: '20px' }}
        color='ff0000'
        iconName='After-the-rain'
      />
      <div>
        <a href='https://vitejs.dev' target='_blank'>
          <img src='/vite.svg' className='logo' alt='Vite logo' />
        </a>
        <a href='https://reactjs.org' target='_blank'>
          <img src={reactLogo} className='logo react' alt='React logo' />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div className='card'>
        <button onClick={() => setCount(count => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className='read-the-docs'>
        Click on the Vite and React logos to learn more
      </p>
    </div>
  )
}

export default App

// vue-ui-test/src/App.vue
<script setup lang="ts">
import HelloWorld from './components/HelloWorld.vue'
// import { IconMaster } from '../../src/vue'
import { IconMaster } from '../../dist/vue'
</script>

<template>
  <div>
    <IconMaster colorRef="ff0000" nameRef="After-the-rain" />
    <a href="https://vitejs.dev" target="_blank">
      <img src="/vite.svg" class="logo" alt="Vite logo" />
    </a>
    <a href="https://vuejs.org/" target="_blank">
      <img src="./assets/vue.svg" class="logo vue" alt="Vue logo" />
    </a>
  </div>
  <HelloWorld msg="Vite + Vue" />
</template>

<style scoped>
._aaaa {
  width: 100px;
}
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
